### ISSUE TITLE
Please add PluginsAPI.dll source code to extend the plugin's API.

### ISSUE THREAD

**Issue by cristiangiagante** [ElevenPaths/FOCA#10]
@jsperk @jaesga  I was checking the Import operations enabled to do Plugins and a lot still being not implemented. Could add the PluginsAPI source code to the repository to extend the api?. If we can work with the Plugin's API we can mantain more cleanest the core of Foca.

Thanks a lot!

**Comment by jsperk** [comment]
It is already available.
