### ISSUE TITLE
SQL Express

### ISSUE THREAD

**Issue by braunweiss** [ElevenPaths/FOCA#103]
Hi I have installed SQL Express 2019 in the basic version. The instance name is .\SQLEXPRESS. When I start Foca, I have the exact same problem as this user:
https://github.com/ElevenPaths/FOCA/issues/95 

The user name is filled out automatically, the password can not be inserted.

I did not change the standard path or anything else.

**Comment by braunweiss** [comment]
I found a solution. You need to start Foca with admin rights

**Comment by iosebyte** [comment]
It is a strange issue, but we are happy you found a solution.
