### ISSUE TITLE
Google api error..

### ISSUE THREAD

**Issue by bymetal** [ElevenPaths/FOCA#104]
Google, bing, duckduckgo. I can not adjust the settings, is there anyone who can tell by video? The error I got on Google (429) too many request. I reset network system and ip problem continues.. Please help.
![errorss](https://user-images.githubusercontent.com/19840118/87688920-41b7bd00-c790-11ea-954c-23cd3c0b5b57.PNG)

**Comment by 123satinder** [comment]
I am getting the same issue. Any suggestions, please.

**Comment by unfunnylord** [comment]
Have you fixed this?

**Comment by iosebyte** [comment]
You should configure Google API. Google Web has a request limit.
https://github.com/ElevenPaths/FOCA/wiki/How-to-set-up-Google-API-search

**Comment by platinumvoid** [comment]
I have configured the API key and CX value but I get the following error:
An error has occurred on GoogleAPI: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

**Comment by iosebyte** [comment]
Are you using the latest release version?
Check if your Foca.exe.config file has the right BindingRedirect for the Newtonsoft assembly.

`    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>`

**Comment by platinumvoid** [comment]
Fixed by downloading from github and then compiling from scratch... (Previously I use an already compiled .exe found here https://foca.en.softonic.com/)

**Comment by iosebyte** [comment]
Nice! We strongly recommend to download Foca only from this github, it's the official repository and we don't known the content of these other sources.

**Comment by Kerolos2004** [comment]
I have configured Google API and followed the steps mentioned here 
https://github.com/ElevenPaths/FOCA/wiki/How-to-set-up-Google-API-search
but when I started searching, I got the following message: GoogleAPI search finished successfully!! Total found result count: 1

How is it even possible to get only 1 result?

**Comment by rubyduty** [comment]
Hello everyone, im trying to learn about foca, and now I have the same error It's unbearable, please, someone who can help me. I also have the Google API

**Comment by wickyramrattan** [comment]
![Image](https://github.com/user-attachments/assets/45b134cc-01dc-48bc-a31e-462f4989c7f7)

Getting still error. Any help

**Comment by AnderVicario** [comment]
> ![Image](https://github.com/user-attachments/assets/45b134cc-01dc-48bc-a31e-462f4989c7f7)
> 
> Getting still error. Any help

same here
