### ISSUE TITLE
ERROR (429) "Too many requests.."

### ISSUE THREAD

**Issue by Drumboll** [ElevenPaths/FOCA#105]
Hello!

I need help, i´m trying to do a Google metadata search, but I recive this error.
![WhatsApp Image 2020-10-03 at 12 06 02 PM (1)](https://user-images.githubusercontent.com/68857284/94997498-1794c080-0571-11eb-90ea-f3eac590e757.jpeg)
![WhatsApp Image 2020-10-03 at 12 06 02 PM](https://user-images.githubusercontent.com/68857284/94997502-1bc0de00-0571-11eb-80cb-b804e558468e.jpeg)

**Comment by kosUskov** [comment]
Just look that https://github.com/ElevenPaths/FOCA/wiki/How-to-set-up-Google-API-search

**Comment by iosebyte** [comment]
Sorry, Google has a request limit per IP address, so if you want to use this engine, yo should use Google API instead of Google Web, as @kosUskov says in his comment
