### ISSUE TITLE
An error occurd on GoogleWeb 429 too many requests

### ISSUE THREAD

**Issue by sparrow-k** [ElevenPaths/FOCA#107]
Hi,
I tried running a scan on a domain, and it all worked fine but after I tried running another one I got this error message:
![image](https://user-images.githubusercontent.com/72691207/100123549-4d746800-2e83-11eb-97ff-31b0047481ec.png)

And it hasn't gone away since. I tried opening wireshark and sniffing to find the relevant 429 status code packet, so I could see how long I need to wait to run another search, but I can't find the packet, which is really weird.

not only that, it seems that it is running the queries fine, I can see all the query packets to google, so I'm not sure why FOCA says it is being blocked.

Does anyone have any solution?
Thank you!

**Comment by xritz0x** [comment]
the same problem

**Comment by legendarynacar** [comment]
I pressume you are not using Google API. Since the requests for Google are HTTPS (See [GoogleWebSearcher.cs](https://github.com/ElevenPaths/FOCA/blob/c2b11a305e717d36116a6e9704a55e8b55109077/SearcherCore/SearcherCore/Searcher/GoogleWebSearcher.cs) ), you can not see the context of request with wireshark. You need ssl inspection, like ZAP or Burp Suite, for that.

I am using Google API and so far I did not have any issues neither error logs nor false positives.

**Comment by iosebyte** [comment]
You should configure Google API. Google Web has a request limit.
https://github.com/ElevenPaths/FOCA/wiki/How-to-set-up-Google-API-search

**Comment by VEYSkub** [comment]
> В pressume вы не используете Google API. Поскольку запросы к Google выполняются по протоколу HTTPS (см. [GoogleWebSearcher.cs](https://github.com/ElevenPaths/FOCA/blob/c2b11a305e717d36116a6e9704a55e8b55109077/SearcherCore/SearcherCore/Searcher/GoogleWebSearcher.cs) ), вы не можете увидеть контекст запроса с помощью wireshark. Для этого вам нужна проверка ssl, например, ZAP или Burp Suite.
> 
> Я использую Google API, и до сих пор у меня не было никаких проблем ни с журналами ошибок, ни с ложными срабатываниями.


I received the API, but the requests ran out quickly.

23:31:55 MetadataSearch error An error has ocurred on GoogleAPI: Google.Apis.Requests.RequestError
Quota exceeded for quota metric 'Queries' and limit 'Queries per day' of service 'customsearch.googleapis.com' for consumer 'project_number:'. [429]
Errors [
 Message[Quota exceeded for quota metric 'Queries' and limit 'Queries per day' of service 'customsearch.googleapis.com' for consumer 'project_number:'.] Location[ - ] Reason[rateLimitExceeded] Domain[global]
]
.
