### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mayank-Khurmai** [ElevenPaths/FOCA#108]
Please add the "How to Download and Install FOCA" in the website/readme.md , because it is quite typical for the beginner to do so.

**Comment by lambardarr** [comment]
> Please add the "How to Download and Install FOCA" in the website/readme.md , because it is quite typical for the beginner to do so.

Bro are you able to install can you please help

**Comment by iosebyte** [comment]
There is a link to the releases page in the readme, and no installation is required, just decompress the downloaded file and execute Foca.exe
