### ISSUE TITLE
Plugin SQLi 

### ISSUE THREAD

**Issue by osnolanarf** [ElevenPaths/FOCA#109]
Tras cargar el plugin SQLi, cargar sqlmap, al lanzar el scan, no termina de ejecutarse nunca. En la ventana de cmd que se abre tras cargar sqlmap, aparecen constantemente estas líneas:

[18:17:05] [DEBUG] (f1eb3c8e77fc7f64) Retrieved scan status

En el administrador de tareas el proceso de python está ejecutándoselo y consumiendo más de 30% de cpu.

Versión de FOCA: 3.4.7.0

**Comment by iosebyte** [comment]
Al parecer el plugin es incompatible con las nuevas versiones de sqlMap.
Lo tendremos en cuenta para futuras releases.
Gracias por el aporte
