### ISSUE TITLE
Excepción en 'PanelMetadaSearch.cs'

### ISSUE THREAD

**Issue by SOACAt** [ElevenPaths/FOCA#11]
Al estar descargando ficheros de un dominio, y invocar IP Bing con Bing Web, da una excepción de acceso invalido a un componente desde un hilo distinto al proceso que lo esta ejecutando.

![excepcionfoca](https://user-images.githubusercontent.com/10871814/34745407-bb28cd02-f590-11e7-9d81-b69800f4292d.PNG)

**Comment by cristiangiagante** [comment]
Podrías escribir los pasos para replicar el bug con detalle? Gracias
PD: Una captura o video serian de mucha ayuda.

**Comment by cristiangiagante** [comment]
@jsperk  creo que podriamos cerrar este issue hasta tener mas novedades

**Comment by iosebyte** [comment]
Closed for inactivity
