### ISSUE TITLE
Projects will not save

### ISSUE THREAD

**Issue by crashcourse7812** [ElevenPaths/FOCA#12]
Whenever I attempt to open a new project, the first error message appears. In some cases it does not allow me to initiate a project, in some cases it does (generally I have to click tasklist first, for whatever reason). Whenever I attempt to save a project, the latter error message appears. So far I have been unable to save any projects and have to reload and redownload everytime I open the application. Any suggestions?

![foca error1](https://user-images.githubusercontent.com/35542264/35064489-385dde04-fb98-11e7-817b-42fcf3745a95.PNG)
![foca error2](https://user-images.githubusercontent.com/35542264/35064490-3870c1d6-fb98-11e7-8bf0-80d395e9802e.PNG)

**Comment by cristiangiagante** [comment]
For your information do you need Microsoft SQL Server Express installed on your local machine to use the open source Foca.
This issue could be related to your db user privileges. Check if your windows user on the db logins have sysadmin role checked.

**Comment by jsperk** [comment]
Thank's @cristiangiagante
