### ISSUE TITLE
Hangs searching for any file

### ISSUE THREAD

**Issue by WitcherDev** [ElevenPaths/FOCA#13]
Hi,
Well it occurred to me lately that FOCA won't find anything. I checked via Google with parameters copied from debug log and it found file -pdf
<img width="564" alt="123" src="https://user-images.githubusercontent.com/15186203/35535914-6bde3ac4-0545-11e8-9c03-cf1e95172d36.png">
It only shows an error with no helpful description. 
<img width="440" alt="234" src="https://user-images.githubusercontent.com/15186203/35535915-6c08def0-0545-11e8-8e23-a9213367ff5a.png">
What is more, it sometimes works but rarely.

**Comment by cristiangiagante** [comment]
@WitcherDev In order to use google metadata search feature do you need set the Google Search Api from Google api services. You did it?

**Comment by JimmyPom** [comment]
Hi, I have the same issue, even when using the API and CX I still don't get any results :-/

**Comment by a56z** [comment]
+1 same problem, why is it that there are sometimes results and sometimes not?

**Comment by cristiangiagante** [comment]
I will check in the weekend and let you know my news guys.

**Comment by fabiorahamim** [comment]
+1 I have the same problem, any solution?
Thanks

**Comment by iosebyte** [comment]
This issue has been solved in 3.4.5.0 version. Check the releases tab.
Thanks
