### ISSUE TITLE
What programm required to modify some features in this program?

### ISSUE THREAD

**Issue by valo376** [ElevenPaths/FOCA#14]
How can i modify this code and what software,OS is needed?
what should i launch? 
and how then can i compile it for running?
i know that my questions maybe not correct,maybe, someone can help me not here, but on my email : 
Vaspitrov@gmail.com 
hope for help

**Comment by jsperk** [comment]
Hi!

You need:
Visual Studio 2017.
Sql Server Express.
Windows 10.

If you never programmed in c # I recommend you read docs about this.
