### ISSUE TITLE
Reporting Module?

### ISSUE THREAD

**Issue by Xeon2476** [ElevenPaths/FOCA#15]
I have installed FOCA 3.4 but I cannot get the reporting module to even show as a option in the menu. Can you help me to understand how to make it appear. 

I have installed Foca 3.4, I have the SQL express, I installed Crystal Reports and I have vistual studio 2013 currently installed (2013 worked well with my last install of FOCA)

**Comment by jsperk** [comment]
Hi!

The latest version of Foca does not use Crystal Report. In the tree view, right click on any option and select the Export to Json option. 

Regards.-
