### ISSUE TITLE
Google APIs

### ISSUE THREAD

**Issue by alexalexro** [ElevenPaths/FOCA#16]
Hello,

The 2 APIs should be only in the options menu(it's not working) or also in the configuration.cs? Which is the format that should be in the configuration file?

Thank you!

**Comment by jsperk** [comment]
Hi!

Im sorry, i don't understand your question. You talk about Google Api , Bing Api or Shodan Api?
Regards.-

**Comment by alexalexro** [comment]
Hi, 
I'm talking about Google API.

**Comment by jsperk** [comment]
Look this link: https://developers.google.com/custom-search/v1/cse/list

And in this proyect you can see how work.
https://github.com/jsperk/GoogleApiSearch

**Comment by iosebyte** [comment]
This issue has been solved in 3.4.5.0 version. Check the releases tab.
Thanks
