### ISSUE TITLE
FOCA	error 	"Couldn't add file, maybe the file is being used or you don't have enough permissions"

### ISSUE THREAD

**Issue by adriendb** [ElevenPaths/FOCA#19]
I receive this error when I click and drag a PDF into Foca.
FOCA Open Source 3.4
Build 3.4.3.0
Running on Windows 10. 
![foca](https://user-images.githubusercontent.com/1918063/44672792-851bad80-a9f7-11e8-9cc0-192688df7e41.png)

**Comment by jsperk** [comment]
Please download the latest version again. If the problem persists, tell me and we review the file.
Regards!

**Comment by iosebyte** [comment]
Closed for inactivity
