### ISSUE TITLE
Documentacion para colaborar

### ISSUE THREAD

**Issue by dokkillo** [ElevenPaths/FOCA#2]
Hola!

Pensais subir documentacion para ayudar a contribuir en este proyecto?

Saludos!

**Comment by plaguna** [comment]
Ademas de la documentación para colaborar seria interesante definir la licencia del código. Saber y conocer de antemano los términos en los que se distribuye el código puede animar a mas gente a colaborar.

**Comment by dokkillo** [comment]
@plaguna  ostras.. no vi que falta la licencia!

**Comment by plaguna** [comment]
Copio y pego de aqui: https://choosealicense.com/no-license/

> When you make a creative work (which includes code), the work is under exclusive copyright by default. **Unless you include a license that specifies otherwise, nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.** Once the work has other contributors (each a copyright holder), “nobody” starts including you.

Hay idea de añadir una licencia al proyecto?

**Comment by dokkillo** [comment]
@plaguna  bueno ya pusieron licencia, es GPL.. pero molesta un poco, que no digan nada, ni un hola... ni nada... solo suben codigo y ya...

**Comment by lolako** [comment]
a todo esto, como se ejecuta el programa? Hace falta la instalación de SQL server?

**Comment by dokkillo** [comment]
@lolako si

**Comment by lolako** [comment]
@dokkillo y la creación de una bd? O la mera instalación?

**Comment by dokkillo** [comment]
@lolako  creo que poniendo en el config el connection string vale.

**Comment by Arian471** [comment]
I am also having trouble running the program, can you make a short documentation/guide?

**Comment by cristiangiagante** [comment]
@lolako You only need Microsoft SQL Express edition installed on the operating system. You don't need any configuration. Only run the program and it self will do the rest.

@Arian471 What is your problem?
