### ISSUE TITLE
Plugin Installation

### ISSUE THREAD

**Issue by a56z** [ElevenPaths/FOCA#20]
Hi I'm trying to install plugins to FOCA but I always get this error message: "Error import plugin." 
I'm following all the steps as described in the videos, e.g. https://www.youtube.com/watch?e=4&v=9maWHe7TWLE and still, I get this message. 

Please clarify what may be the reason that plugins are not recognised
(I'm from Mac/Linux background, first time using Windows, so probably I'm missing something very basic here!)

Cheers,
a56z

**Comment by jsperk** [comment]
Corrected in another existing issue. 
Regards!
