### ISSUE TITLE
Zero filesize of downloaded files

### ISSUE THREAD

**Issue by HydroSausager** [ElevenPaths/FOCA#23]
Hello, i tried search and downloading files frome some different domains, but all times the probles is what the filesize is 0...
win7x64, sql exp 2014
![issue](https://user-images.githubusercontent.com/45184745/49760981-ce59e980-fcd6-11e8-82d6-a75cc3e7daf1.png)

**Comment by cristiangiagante** [comment]
Could you send us step to reproduce this behavior?, you use the builtin Foca version or you are running it from visual studio?

**Comment by HydroSausager** [comment]
i am using a 3.4.3 release version

**Comment by iosebyte** [comment]
Could you send us some Urls to check this bug?

**Comment by iosebyte** [comment]
Closed for inactivity

**Comment by erickmca** [comment]
Hi.

I have the same problem. When I download files, they are 0 filesize. I can´t analyzed it.
