### ISSUE TITLE
Direcotiro Foca release no esta visible

### ISSUE THREAD

**Issue by cquilodevelop1981** [ElevenPaths/FOCA#25]
Par ainstalar foca en windows no aparece el Foca .exe que nrmalmente estaba disponbile en el diectorio Foca release.
El otro caso es que en Linux , en los tutoriales disponbles no se adecuanal contenido actual del repo en git....
https://github.com/ElevenPaths/FOCA

- Por favor indicar si la forma de ejecutar foca en windows ha cambiado y si ya no es necesario foca .exe
- Y tambien si pueden colocar los links para la guia de instalacion de FOCA en verisond elinux ubuntu 16, 18
Saludos.
CQ.

**Comment by iosebyte** [comment]
Hola, se ha hecho una limpieza y se  han eliminado los binarios del código fuente.
Para descargarlos puedes acceder a las releases del proyecto, que es como github los gestiona.
https://github.com/ElevenPaths/FOCA/releases

Respecto a linux, no se da soporte a este plataforma, al menos de momento.

Gracias

**Comment by cquilodevelop1981** [comment]
Hola,
Tengo windows 10. Del enlace que me enviaste, yo baje el archivo 
https://github.com/ElevenPaths/FOCA/releases/download/v3.4.3/Foca-v3.4.3.zip
pero los otros dos archivos no:
Source code(zip)
Source code (tar)
Al bajar el primer archivo a mi unidad C o D, ejecuto FOCA.exe, pero windows 10 no puede abrirlo
y de pronto de cierra con el mensaje "FOCA (OPen Source) dejo de funcionar El programa dejo de funcionar correctamente por un problmea. Windows cerrara ...."
Cual podria ser problema?....falta algo por descargar o algun complemento por el cual no pueda correr en windows 10?
Por favor me das una mano con esto?
Saludos,
