### ISSUE TITLE
Can't use SQL Server Enterprise

### ISSUE THREAD

**Issue by MayconRobert** [ElevenPaths/FOCA#28]
I have SQL Server 2017 Enterprise registered but I still get the error when starting, saying that I need a database.

I tested in two different machines, both of them working and with Enterprise version installed. I tested some programs I made and the SQL Server is running with no problems.

**Comment by iosebyte** [comment]
Hi,
nowadays Foca only works with SQL Express version installed on the same machine that Foca runs.
We will work to improve this.

Thanks
