### ISSUE TITLE
Cannot load plugins

### ISSUE THREAD

**Issue by texereda** [ElevenPaths/FOCA#30]
Hello FOCA team,

today I've installed the Foca v3.4.3.1 package (https://github.com/ElevenPaths/FOCA/releases/download/v3.4.3.1/Foca-v3.4.3.1.zip), on my Windows 10 box, but unfortunately I cannot load plugins.

The error is "Error import plugin.", the source path for the plugins is C:\<My User Desktop Folder>\OSINT\Foca-v3.4.3.1\Plugins

Can you please suggest a fix ? I tried the fix suggested here: https://github.com/ElevenPaths/FOCA/issues/20 but it does not work for me.

Thank you !

**Comment by iosebyte** [comment]
Hello,
Windows 10 uses SmartScreen to prevent the execution of potentially malicious content.
When you download the application from an untrusted website, windows locks the application.
To solve this, you have to unblock all the plugin files, like in this image:

![image](https://user-images.githubusercontent.com/4988743/57918229-9e6ecd80-7896-11e9-96e3-a29512750435.png)

Then you have to restart Foca, and load plugins again

**Comment by texereda** [comment]
Hello,

that solved the issue, thank you and sorry for the delay in the reply !
