### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Dig1talXen0morph** [ElevenPaths/FOCA#43]
There is no bin folder, hence there is no FOCA.exe file. 

How are you supposed to run the program? Thanks

**Comment by iosebyte** [comment]
If you have cloned the repository, you should compile it to generate an executable file.
But if you only want the executable file, download the latest release from https://github.com/ElevenPaths/FOCA/releases

**Comment by Dig1talXen0morph** [comment]
Thanks, I appreciate it. Perhaps it would be good if you could add it somewhere in Readme notes
