### ISSUE TITLE
Petición: Soporte de proxy y user-agent

### ISSUE THREAD

**Issue by againtoday** [ElevenPaths/FOCA#5]
Buenas.

Sería posible que se añadiera soporte de proxy como en la versión Pro, y poder personalizar el user-agent?

Muchas Gracias.

**Comment by cristiangiagante** [comment]
Here you have a plugin to set windows global proxy with foca http://github.com/cristiangiagante/proxypluginfoca

**Comment by jsperk** [comment]
Excellent plugin @cristiangiagante , thanks!

Regards,
