### ISSUE TITLE
eats all my RAM when running scan

### ISSUE THREAD

**Issue by fedelaport** [ElevenPaths/FOCA#6]
Look at this:
https://imgur.com/F48aSYQ
FOCA is eating a lot of RAM. Somebody knows wtf is happening?

**Comment by cristiangiagante** [comment]
It's normal, take this references (spanish)
http://www.elladodelmal.com/2013/01/foca-intruder-usando-foca-burp-intruder.html
Chema Alonso says that Foca requires between 4 and 8 gb of ram depending the size of the domain to scan.
