### ISSUE TITLE
Crash on Windows Server 2012 R2

### ISSUE THREAD

**Issue by Hipapheralkus** [ElevenPaths/FOCA#7]
I downloaded it and started, I get following:
```
FOCA (Open Source) stopped working.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	FOCA.exe
  Problem Signature 02:	3.4.3.0
  Problem Signature 03:	59d39418
  Problem Signature 04:	System.ServiceProcess
  Problem Signature 05:	4.6.1590.0
  Problem Signature 06:	5787eeaa
  Problem Signature 07:	65
  Problem Signature 08:	196
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	1033
  Additional Information 1:	b3b0
  Additional Information 2:	b3b024c85749ae2b2617e68ae63fc4da
  Additional Information 3:	b361
  Additional Information 4:	b361eb42c9882c3c3635a4da5c874e0a

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

```
I don't really know how more can I be helpful, are there any logs/information which might help? I can reproduce it at any time because it won't run at all. Even when I tried to change compatibility to Windows 7...
Thanks

EDIT: looks like this: 
![image](https://user-images.githubusercontent.com/4717664/33273980-2828f9c8-d38f-11e7-9bf8-89ea534c5820.png)

**Comment by leptoid** [comment]
I had this happen too.  To fix it, I had to install MSSQLServer Express, even though I have MSSQL Server installed.
[](https://www.microsoft.com/en-us/sql-server/sql-server-editions-express)

Anyhow, once it installs, FOCA 3.4.3.0 works.

**Comment by cristiangiagante** [comment]
I send a pull request with the fix to prevent the crash and open the window alert dialog reporting that MSSQL-EXPRESS is required.
