### ISSUE TITLE
Unable to find bin folder

### ISSUE THREAD

**Issue by ssosts1** [ElevenPaths/FOCA#76]
I might be missing something very obvious here but I can not find either bin folder or executable file to install FOCA.
Just to clarify, I downloaded the zip file.

**Comment by Argaide** [comment]
Hello ssosts1,

First of all, thank you for your interest in using FOCA, we appreciate it. 

Currently, there is no _.exe_ in the _bin folder_ as you are looking for. You can download our latest release from the releases page here: https://github.com/ElevenPaths/FOCA/releases 

Just out of curiosity, could you tell us where you found this information about the _.exe_ in the _bin folder_? We would want to keep all the outdated information in check.

**Comment by ssosts1** [comment]
Thank you for the reply.
I vaguely remember researching some tools for blue teaming & came across a video on Youtube showing what the tool is capable of. I am pretty sure the demonstrator extracted the file & run the executable from bin folder.Hope this helps.

**Comment by Argaide** [comment]
Very helpful, we know which is the video you are referring to.

If you have any other question, please don't hesitate to contact us.
