### ISSUE TITLE
Failed to detect pdf file type ("df") file type detected instead

### ISSUE THREAD

**Issue by Hipapheralkus** [ElevenPaths/FOCA#8]
When the URL doesn't end with PDF (although Google results were successfully parsed and given file is indeedn a pdf file); FOCA won't recognize it. Instead of "pdf", the detected file type is "df":
![df files](https://user-images.githubusercontent.com/4717664/33272808-9ef81646-d38b-11e7-94f5-233d667fbd3e.png)

**Comment by cristiangiagante** [comment]
I can't replicate this bug.
![poc3](https://user-images.githubusercontent.com/7245667/34501754-1bef9424-efef-11e7-965a-7e0beee4ca2b.png)
