### ISSUE TITLE
Que tal pasar FOCA a .Net Core?

### ISSUE THREAD

**Issue by g4rc1ss** [ElevenPaths/FOCA#83]
Pues eso...
Que tal seria pasar FOCA de .Net Framework a .Net Core? Estaria mas "a la ultima" por decirlo asi... Y el framework .Net Core saca mejores resultados en velocidad etc que .Net Framwork :P

**Comment by iosebyte** [comment]
Hola! Antes de nada gracias por tu propuesta. Es algo que llevamos valorando internamente desde hace un tiempo, y aunque a futuro la idea es migrarlo, tenemos trabajo previo que realizar.

Muchas gracias :)
