### ISSUE TITLE
GoogleWeb Error

### ISSUE THREAD

**Issue by Folkston** [ElevenPaths/FOCA#87]
I can't any metadata using GoogleWeb searching. 
Always get "Error found searching in GoogleWeb".
Any thoughts?

**Comment by iosebyte** [comment]
Hello,

It appears that you are using an old FOCA version.

Could you download the latest release and try it again?

Thanks for the report

**Comment by Folkston** [comment]
Hey!
I installed the last version and reinstalled SQL Express.
Now it works great, thank you a lot for replying!
