### ISSUE TITLE
Descarga de archivos con tamaño 0

### ISSUE THREAD

**Issue by erickmca** [ElevenPaths/FOCA#90]
Cuando descargo archivos encontrados en la sección de metada, estos se descargan con tamaño de 0 kbs, por lo que no tiene metadatos que extraer. Estoy usando la última version (3.4.6.2), corriendo directamente el archivo .exe descargado desde el .zip de la pagina de releases.

**Comment by Argaide** [comment]
Hola, 

Antes de nada, muchas gracias por tu mensaje.

No soy capaz de reproducir el comportamiento que comentas. Necesitariamos un poquito más de información del escenario si no es molestia. 

- ¿Con qué dominio (_Domain website_) estás probando? ¿Ocurre lo mismo con todos los dominios que pruebas?

- ¿Con qué buscadores estás trabajando?

- ¿Qué tipos de fichero estás buscando?

- El campo _Size_ se calcula cuando la fase de búsqueda ha acabado y puede tardar un poquito en ser calculado si se han encontrado muchos ficheros. Aún así, si se pincha con el botón secundario y se elije la descarga del fichero (_Download_ y _Download All_) los ficheros se descargan aunque el _Size_ no haya sido calculado. ¿Cuándo intentas descargar qué comportamiento observas?

**Comment by erickmca** [comment]
Hola.

El dominio que uso es educacioncampeche.gob.mx. Probe con otro dominio y si me descargó archivos, por alguna razón los del dominio de educación no los descarga. Probé también con la versión anterior de FOCA Pro y si realiza las descargas en el domino mencionado. Probé también con los tres buscadores (Google, Bing y Duck Duck go) pero no más no descarga.

**Comment by iosebyte** [comment]
Hola!
Gracias por la respuesta.
Lamentablemente, ese dominio tiene una protección anti-DDoS de CloudFlare, para evitar navegación que no sea mediante navegador. Asi que evita que Foca pueda descargar ficheros.

Sentimos no poder hacer nada. Gracias
