### ISSUE TITLE
Needs a SQL Database although SQL Express is installed

### ISSUE THREAD

**Issue by Individuum92** [ElevenPaths/FOCA#95]
I have installed the SQL Express 2019 sucessfully and run FOCA. 
Unfortunatelly, i receive the message that FOCA needs a SQL databse and i have to setup a databse connection. 
Same problem with SQL Express 2017.

**Comment by Argaide** [comment]
Hello,

Indeed, FOCA needs a connection to the database of your preference to start working. If no default connection is configured, the system will prompt a window for introducing a connection string.

To help you further, could you please send us a screenshot of the error?

**Comment by Individuum92** [comment]
Hi,

thanks for the answer. 
After i installed SQL Express 2019 with default configuration i started FOCA.
Screenshot of the error below.

![Unbenannt](https://user-images.githubusercontent.com/18618181/74327648-d5720100-4d8c-11ea-8eaa-488bc986fce8.PNG)

**Comment by Argaide** [comment]
After you click the OK button. Don't you see a window similar to this one?:

![image](https://user-images.githubusercontent.com/2765830/74428952-4f23f080-4e5a-11ea-95d4-8339f92b6b66.png)

Yo need to enter the connection information here.

**Comment by Individuum92** [comment]
Yes, i do. But i can not change the fields "User name" and "Password". 
The User name was set automatically.

![Unbenannt](https://user-images.githubusercontent.com/18618181/74439434-800d2100-4e6c-11ea-86bb-67e0ac4e9ec7.PNG)

**Comment by Argaide** [comment]
If you choose to use _Windows authentication_ then, there's really nothing left to configure but checking that the  _Server name_ is correct. 

Could it be that you changed the SQL instance name during the installation process?

For further information, you can check out our wiki tutorial about setting the SQL database. 

https://github.com/ElevenPaths/FOCA/wiki/How-to-set-up-a-SQL-database-connection

**Comment by ourenseko** [comment]
> If you choose to use _Windows authentication_ then, there's really nothing left to configure but checking that the _Server name_ is correct.
> 
> Could it be that you changed the SQL instance name during the installation process?
> 
> For further information, you can check out our wiki tutorial about setting the SQL database.
> 
> https://github.com/ElevenPaths/FOCA/wiki/How-to-set-up-a-SQL-database-connection

It possible do it with MariaDB? I have tried put in server name "localhost" but it not connect.

**Comment by Argaide** [comment]
Hello ourenseko,

Unfortunately, we haven't tried connecting FOCA with MariaDB. We guess that may be possible with the right drivers, but sadly, we have no experience that would help you navigate through it.

Please, if you succeed, let us know!

**Comment by Individuum92** [comment]
I tried many things, but FOCA with the name ".\SQLSERVER" was not executed for the database.
If I use "localhost" FOCA runs without problems! : =)

**Comment by SAMA13KNOT** [comment]
> I tried many things, but FOCA with the name ".\SQLSERVER" was not executed for the database.
> If I use "localhost" FOCA runs without problems! : =)

Thanks!! :)
